import { Geist, Geist_Mono, Cairo } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import I18nProvider from "./I18nProvider.jsx";
import AOSProvider from "./AOSProvider.jsx";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const cairo = Cairo({
    variable: "--font-cairo",
    subsets: ["arabic", "latin"],
    weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} antialiased`} suppressHydrationWarning>
                <I18nProvider>
                    <AOSProvider>
                        {children}
                    </AOSProvider>
                </I18nProvider>
            </body>
        </html>
    );
}